openapi: 3.0.9
info:
  title: Tic Tac Toe
  description: |
    This API allows writing down marks on a Tic Tac Toe board
    and requesting the state of the board or of individual squares.
  version: 1.0.0

paths:
  # Whole board operations
  /boards/{id_board}:
    get:
      summary: Get the whole board from its ID.
      description: Retrieves the current state of board and the winner.
      parameters:
        - $ref: "#/components/parameters/id_board"
      responses:
        200:
          description: The current board for ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/200_boards"
        404:
          description: No board was found from the given ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/404_boards"
        500:
          description: Internal Server Error

components:
  parameters:
    id_board:
      description: Board ID.
      name: id_board
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/id_board"

  schemas:
    id_board:
      type: number
      minimum: 1
    200_boards:
      type: object
      properties:
        board:
          $ref: "#/components/schemas/board"
    board:
      type: object
      properties:
        teams:
          type: array
          maxItems: 2
          minItems: 2
          description: The two rivals teams.
          items:
            $ref: "#/components/schemas/team"
        winnerId:
          type: number
          default: null
          nullable: true
        matchEnded:
          type: boolean
          default: false
    team_to_update:
      type: object
      $ref: "#/components/schemas/team"
    team:
      type: object
      properties:
        id:
          type: number
          minimum: 1
        teamName:
          type: string
        score:
          type: number
          minimum: 0
    404_boards:
      type: object
      properties:
        code:
          type: number
          example: 404
        message:
          type: string
          example: Not Found
